In [1]:
#importing the required libraries
import numpy as np
import pandas as pd

In [2]:
#load the array into a variable and converting them to a dataframe
arr = np.load('S_new.npy')
data_f = pd.DataFrame(arr)
data_f.head()

0
0  13.266400
1   7.310945
2   4.689716
3   0.890135
4   0.516667

In [3]:
#load the array into a variable and converting them to a dataframe
arr1 = np.load('U_new.npy')
data1_f = pd.DataFrame(arr1)
data1_f.head()

0         1         2         3         4
0 -0.423445  0.556656 -0.241025  0.330546 -0.245622
1 -0.506993 -0.477910 -0.164953  0.379532  0.583310
2 -0.373355  0.506098 -0.191829 -0.473431  0.385749
3 -0.344477  0.128204  0.633886  0.412236 -0.237219
4 -0.424225 -0.407911 -0.386011 -0.252589 -0.627057

In [4]:
#load the array into a variable and converting them to a dataframe
arr2 = np.load('V_transpose_new.npy')
data2_f = pd.DataFrame(arr2)
data2_f.head()

0         1         2         3         4
0 -0.433991 -0.406137 -0.424654 -0.461054 -0.503789
1  0.559634  0.538641 -0.087827 -0.380015 -0.494521
2 -0.078209 -0.208129  0.894477 -0.305012 -0.239675
3  0.425915 -0.488806 -0.011195  0.579464 -0.493722
4 -0.557621  0.512514  0.108355  0.462824 -0.447705

In [5]:
# read in the U, S, V arrays from disk
U = np.load('U_new.npy')
S = np.load('S_new.npy')
V = np.load('V_transpose_new.npy')

In [6]:
U

array([[-0.42344517,  0.55665609, -0.24102467,  0.3305458 , -0.24562245],
       [-0.50699337, -0.47790996, -0.16495257,  0.37953185,  0.58331032],
       [-0.37335489,  0.50609813, -0.19182881, -0.4734306 ,  0.385749  ],
       [-0.34447683,  0.12820357,  0.63388605,  0.41223622, -0.23721861],
       [-0.42422527, -0.40791144, -0.38601146, -0.2525886 , -0.62705737],
       [-0.35443853, -0.15090679,  0.57191179, -0.53741866,  0.033805  ]])

In [7]:
S

array([13.2663997 ,  7.31094493,  4.68971622,  0.89013458,  0.51666749])

In [8]:
V

array([[-0.43399074, -0.40613677, -0.42465386, -0.46105389, -0.50378901],
       [ 0.55963405,  0.53864051, -0.08782676, -0.38001516, -0.49452105],
       [-0.07820851, -0.20812855,  0.89447713, -0.30501222, -0.23967508],
       [ 0.42591506, -0.48880552, -0.01119466,  0.57946426, -0.49372196],
       [-0.55762134,  0.51251438,  0.10835544,  0.46282448, -0.44770531]])

In [9]:
A = np.matmul(np.diag(S),V)
A

array([[-5.75749462, -5.38797273, -5.63362784, -6.11652519, -6.68346637],
       [ 4.09145372,  3.93797111, -0.64209661, -2.77826991, -3.61541616],
       [-0.36677572, -0.97606384,  4.19484391, -1.43042076, -1.12400811],
       [ 0.37912172, -0.43510269, -0.00996475,  0.51580117, -0.43947899],
       [-0.28810482,  0.26479952,  0.05598373,  0.23912636, -0.23131478]])

In [10]:
B = np.matmul(U,A)
B

array([[5.00000001, 4.5       , 0.99999997, 1.49999999, 0.99999999],
       [0.99999998, 1.00000004, 2.5       , 4.99999999, 4.99999997],
       [4.00000001, 4.5       , 0.99999997, 0.99999999, 0.99999999],
       [2.5       , 1.50000002, 4.49999998, 1.        , 0.99999998],
       [0.99999998, 1.00000003, 1.        , 4.        , 4.99999998],
       [0.99999999, 1.00000002, 4.49999999, 1.5       , 2.49999998]])

In [11]:
# Found the complete rating matrix
rating_matrix = B

In [12]:
rating_matrix

array([[5.00000001, 4.5       , 0.99999997, 1.49999999, 0.99999999],
       [0.99999998, 1.00000004, 2.5       , 4.99999999, 4.99999997],
       [4.00000001, 4.5       , 0.99999997, 0.99999999, 0.99999999],
       [2.5       , 1.50000002, 4.49999998, 1.        , 0.99999998],
       [0.99999998, 1.00000003, 1.        , 4.        , 4.99999998],
       [0.99999999, 1.00000002, 4.49999999, 1.5       , 2.49999998]])

In [13]:
# (1 point) a) What is U1’s ‘estimated’ rating of the movie Amelie?
rating_matrix[0][3]

1.4999999898595036

In [14]:
#(2 point) b) What is the strength of concept 1 in the SVD decomposition?
S[0]

13.266399703684902

In [15]:
#(1 point) c) What is the average rating for movie Harry Potter across all users in the system (i.e., if actual
#ratings exist, use them if not use estimated ratings)?
a = sum(rating_matrix[:,2])/len(rating_matrix[:,2])
print("Average Rating for Harrypotter Movie is ",round(a,2))

Average Rating for Harrypotter Movie is  2.42


In [16]:
# (1 point) d) What is the movie with the overall highest rating (i.e., if actual ratings exist, use them if not
#use estimated ratings)?
a = np.nanargmax(np.nanmean(rating_matrix, axis=0))
a

4

In [17]:
#Therefore, the movie at index 4 is Casablanca which is the hightest rated movie